### ISSUE TITLE
pybo becomes pybo + botok

### ISSUE THREAD

**Issue by drupchen** [BLKSerene/Wordless#11]
Not really an issue, but in your next releases, you might want to use botok instead of pybo.
Everything is the same except for the import line.

All the codebase related to the Tibetan tokenizers has been moved to botok. pybo is now a toolbox that imports and uses botok amongst others and provide a convenient command line interface for standard operations.

**Comment by BLKSerene** [comment]
Thanks for the information! I'll keep it in mind.

**Comment by BLKSerene** [comment]
Resolved in [v1.3.0](https://github.com/BLKSerene/Wordless/releases/tag/v1.3.0).
