### ISSUE TITLE
高分屏适配问题

### ISSUE THREAD

**Issue by BGMjie** [BLKSerene/Wordless#12]
笔记本4k高分屏看起来眼睛要瞎了，求大佬做下适配

**Comment by BLKSerene** [comment]
是字太小嘛 设置里可以把字体改大 下一版本我试试看怎么适配 我之前也没考虑过这个问题

在 2020-10-09 21:52:08，BGMjie <notifications@github.com> 写道：


笔记本4k高分屏看起来眼睛要瞎了，求大佬做下适配

**Comment by BLKSerene** [comment]
设置里可以调整字体大小 另外下一版也会尝试改进
