### ISSUE TITLE
请问可否添加dpi适应？

### ISSUE THREAD

**Issue by rosie-law** [BLKSerene/Wordless#14]
使用matebook x pro，不知道是不是分辨率问题（3k x 2k）搭配的缩放200%，页面的字就算设置到extra large还是很小很小呢
![微信截图_20210417174929](https://user-images.githubusercontent.com/82701340/115108863-49b5bf00-9fa5-11eb-995f-cd086945eb50.png)

**Comment by BLKSerene** [comment]
高分屏的字体适配问题后续版本会逐步尝试解决

**Comment by BLKSerene** [comment]
[2.3.0](https://github.com/BLKSerene/Wordless/releases/tag/2.3.0) 中已添加对苹果 Retina 高分屏的支持

Windows 和 Linux 用户可以在菜单 - Preferences - Settings - General - User Interface Settings - Interface Scaling 指定全局缩放系数（界面+字体） 下面 Font Size 也可以单独修改字体大小
