### ISSUE TITLE
打开的的文件编码等下拉列表不应支持mouseover后滑动滚轮就更改值的操作

### ISSUE THREAD

**Issue by fishfree** [BLKSerene/Wordless#2]
可参考： https://stackoverflow.com/questions/3241830/qt-how-to-disable-mouse-scrolling-of-qcombobox

**Comment by BLKSerene** [comment]
感谢建议 [v1.1.0](https://github.com/BLKSerene/Wordless/releases/tag/v1.1.0) 中已改进
