### ISSUE TITLE
Problem with Generating Word Cloud containing Chinese Characters

### ISSUE THREAD

**Issue by aarondeng** [BLKSerene/Wordless#20]
![图片](https://user-images.githubusercontent.com/4115144/163582275-cbf49942-07e3-4b52-8071-6b765c512e36.png)

**Comment by BLKSerene** [comment]
To display Chinese characters (or other non-Latin letters) in word clouds, change Preferences - Settings - Figures - Word Cloud - Font to "Unifont".
