### ISSUE TITLE
Frequent crashes for some operations (N-gram, etc)

### ISSUE THREAD

**Issue by yanqianglu** [BLKSerene/Wordless#21]
Hi,

I have a few documents mixed in Tibetan and Chinese. I found Wordless would crash multiple times, especially for n-gram, collocation extractor. 

I'm not sure if that's because of the size of the corpus. From the profiler, there are 10909 paragraphs, and 172885 tokens, 581964 characters. I remember I tried with small files, but the app crashed too. 

I'm on macOS 12.3.1 with M1 Pro chip. I tried another Macbook with intel chip but had the same experience. Wordless version: 2.2.0.

The path to Wordless doesn't have any non-ASCII characters, though file names are in Tibetan and Chinese. 

I do have the crash report that generated by the system, but not sure if that's helpful. Please let me know what other information are needed for investigation. 

Thanks

**Comment by BLKSerene** [comment]
There is a bug for the macOS version which should be fixed in the next version. You may use the Windows version now.

**Comment by BLKSerene** [comment]
Fixed in [2.3.0](https://github.com/BLKSerene/Wordless/releases/tag/2.3.0), please take a try.

**Comment by BLKSerene** [comment]
Fixed in [2.3.0](https://github.com/BLKSerene/Wordless/releases/tag/2.3.0), please take a try.
