### ISSUE TITLE
无法打开程度

### ISSUE THREAD

**Issue by Dborgia** [BLKSerene/Wordless#39]
叶博士您好：

之前导入了一个较大的TMX， 然后进行一个次平行索引。索引中途报错，MEMORY ERROR
关掉程序后再打开就无法打开了
报错为
Traceback (most recent call last):
  File "wordless\wl_main.py", line 1249, in <module>
EOFError: Ran out of input

于是我在网上下了3.5版的，结果打开还是同样的报错。

现在应该怎么办呢？

**Comment by BLKSerene** [comment]
你好 memory error 是单纯的电脑可用内存不够 这个只能用 Wordless 的时候关掉其他程序或者把文件切小一点 分批次搜索

**Comment by Dborgia** [comment]
谢谢
