### ISSUE TITLE
Figure里的中文有乱码

### ISSUE THREAD

**Issue by fishfree** [BLKSerene/Wordless#4]
是否可考虑替换成Noto Sans字体？ https://leonax.net/p/7750/use-noto-sans-cjk-as-default-blog-font/

**Comment by BLKSerene** [comment]
您好 [v1.2.0](https://github.com/BLKSerene/Wordless/releases/tag/v1.2.0)中已解决
Word Cloud 默认字体已修改为 Code2000 有些汉字如果还是显示不出来可在 Settings -> Figures -> Word Cloud 中修改字体为 Unifont 即可
Line Chart 和新添加的 Network Graph 也可在此处修改字体（只能选择系统中已安装的字体）

至于 Noto Sans 是一整套字体 Noto Sans CJK 能显示中文 但显示不了藏文 梵文等其他字母 对于哪些语言分别用的是哪些字母我也并不是特别确定 所以无法自动切换 而且 Noto Sans 全部字体有 1G 多 打包进来实在太占空间 一般用户对哪种语言有研究需求 系统上都会安装相应的字体 所以由用户自行选择系统上已安装的字体即可 也省去了打包大量字体文件并对不同语言自动匹配不同字体的问题
