### ISSUE TITLE
导入TMX文件时出错

### ISSUE THREAD

**Issue by Dborgia** [BLKSerene/Wordless#43]
叶博士您好
我在导入TMX文件时出错，报错为
Traceback (most recent call last):
  File "wordless\wl_file_area.py", line 1029, in run
ValueError: not enough values to unpack (expected 2, got 1)

应该不是文件的问题，我用AntConc可以打开，也可以检索

**Comment by BLKSerene** [comment]
你好 用的什么版本呢 TMX 文件方便发我测试下吗

**Comment by Dborgia** [comment]
3.5，我一会儿发您邮箱

**Comment by BLKSerene** [comment]
你好 文件已收到 TMX文件里有两行正文里的左尖括号没有替换为对应的实体符号 导致XML标签无法正确识别 邮件里已具体回复
