### ISSUE TITLE
打开程序出错

### ISSUE THREAD

**Issue by Dborgia** [BLKSerene/Wordless#44]
叶博士您好

     突然不能打开我程序了，报错是
     Traceback (most recent call last):
  File "wordless\wl_main.py", line 125, in <module>
EOFError: Ran out of input
     <img width="887" alt="屏幕截图 2024-12-13 161338" src="https://github.com/user-attachments/assets/ba1adb94-b8fd-4216-857b-2a4f3b6d5831" />

   
     我下载了一个新的打开即用的版本，但是打开依然是这个问题。
     因为我之前有导入很多文档，所以不想重新安装 ，这种情况应该怎么办呢？

**Comment by BLKSerene** [comment]
这个应该是关闭程序的时候导入的文件没来得及保存导致的
因为设置文件应该已经损坏了 只能删掉目录下的 wl_settings.pickle 文件后重启
所有设置包括之前加载的文件都会重置 文件数量太多的话建议稍微合并一下

**Comment by Dborgia** [comment]
好的，可以打开了，谢谢！

**Comment by BLKSerene** [comment]
[Wordless 3.6.0](https://github.com/BLKSerene/Wordless/releases/tag/3.6.0) 已发布 现在出现该问题时会自动重置设置并提示用户 不会再报错了
