### ISSUE TITLE
汉语的云图出现方格显示不了汉语词汇

### ISSUE THREAD

**Issue by lkqlkqlkqlkqlkq** [BLKSerene/Wordless#6]

**Comment by BLKSerene** [comment]
您好 [v1.2.0](https://github.com/BLKSerene/Wordless/releases/tag/v1.2.0)中已解决 默认的 Code2000 可能还有一些汉字显示不出来 可在 Settings -> Figures -> Word Cloud 中修改字体为 Unifont 即可显示
另外 Line Chart 和新添加的 Network Graph 也可在这里对字体进行修改

**Comment by lkqlkqlkqlkqlkq** [comment]
您好，谢谢反馈。
经重新设置后的确可显示词云图，但较模糊。

---原始邮件---
发件人: &quot;BLKSerene&quot;<notifications@github.com&gt;
发送时间: 2019年8月27日(星期二) 晚上11:00
收件人: &quot;BLKSerene/Wordless&quot;<Wordless@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;lkqlkqlkqlkqlkq&quot;<lc1971@qq.com&gt;;
主题: Re: [BLKSerene/Wordless] 汉语的云图出现方格显示不了汉语词汇 (#6)



您好 v1.2.0中已解决 默认的 Code2000 可能还有一些汉字显示不出来 可在 Settings -&gt; Figures -&gt; Word Cloud 中修改字体为 Unifont 即可显示
 另外 Line Chart 和新添加的 Network Graph 也可在这里对字体进行修改
 
&mdash;

**Comment by BLKSerene** [comment]
这个是 Unifont 这个字体本身的问题 这个字体基本支持常见的Unicode字符 所以涵盖的语种比较多 但相对字符是像素格式的 比较难看
可以到 Wordless/wordcloud 这个目录下 三个TTF文件分别对应设置里的三个选项（DroidSansMono Code2000 Unifont） 可以自行把其中一个替换中汉语的专用字体（文件名注意还是unifont-12.1.03.ttf 不然没法识别）

**Comment by lkqlkqlkqlkqlkq** [comment]
收到，确有显示改善。谢谢！

---原始邮件---
发件人: &quot;BLKSerene&quot;<notifications@github.com&gt;
发送时间: 2019年8月28日(星期三) 下午5:49
收件人: &quot;BLKSerene/Wordless&quot;<Wordless@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;lkqlkqlkqlkqlkq&quot;<lc1971@qq.com&gt;;
主题: Re: [BLKSerene/Wordless] 汉语的云图出现方格显示不了汉语词汇 (#6)



这个是 Unifont 这个字体本身的问题 这个字体基本支持常见的Unicode字符 所以涵盖的语种比较多 但相对字符是像素格式的 比较难看
 可以到 Wordless/wordcloud 这个目录下 三个TTF文&#x4EF6;分别对应设置里的三个选项（DroidSansMono Code2000 Unifont） 可以自行把其中一个替换中汉语的专用字体（文&#x4EF6;名注意还是unifont-12.1.03.ttf 不然没法识别）
 
&mdash;
