### ISSUE TITLE
各项统计结果都是0

### ISSUE THREAD

**Issue by louislaolu** [BLKSerene/Wordless#9]
用wordless分析奥巴马的演讲A Just and Lasting Peace Nobel Peace Prize Lecture Oslo, Noway, December 10, 2009
出现如下提示：
Data processing has completed successfully, but there are no results to display. You can change your settings and try again.
是因为文章太短了吗？该怎么设置？

**Comment by louislaolu** [comment]
[A Just and Lasting Peace Nobel Peace Prize Lecture Oslo, Noway, December 10, 2009.txt](https://github.com/BLKSerene/Wordless/files/3379550/A.Just.and.Lasting.Peace.Nobel.Peace.Prize.Lecture.Oslo.Noway.December.10.2009.txt)

**Comment by louislaolu** [comment]
[A Just and Lasting Peace.txt](https://github.com/BLKSerene/Wordless/files/3379623/A.Just.and.Lasting.Peace.txt)

**Comment by BLKSerene** [comment]
您好 文本看着没什么问题 应该是设置的问题
请问是哪个模块？底下的文件设置和右边的详细设置是怎么样的？
最好截个完整的软件图

**Comment by louislaolu** [comment]
![image](https://user-images.githubusercontent.com/49530902/61038498-0a684080-a3c5-11e9-8f4d-529c81292bfa.png)

**Comment by louislaolu** [comment]
谢谢回复。已经解决了，编码选错了。
